title: The Phoenix Division - Impressum
description: Impressum for The Phoenix Division websites and social platforms.
show_downloads: false
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
